version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install dependencies needed for running tests
      - npm i -g serverless
      - npm install

      # Upgrade AWS CLI to the latest version
#      - pip install --upgrade awscli

  build:
    commands:
      - sls deploy -s dev -v
