service: ${self:custom.service}

custom:
  service: ${file(./config.json):service}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, '${file(./config.json):region}'}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}

functions:
  runReminder:
    handler: handler.runReminder
    environment:
      TRELLO_API_KEY: ${env:TRELLO_API_KEY}
      TRELLO_OAUTH_TOKEN: ${env:TRELLO_OAUTH_TOKEN}
      MEMBER_ID: ${env:MEMBER_ID}
    events:
      - schedule:
          name: perfsys-trello-reminder-runReminder-rate-event
          description: 'perfsys-trello-reminder-runReminder-rate-event'
          rate: rate(30 minutes)
          enabled: true
